---
- include_tasks: kasm-state.yml
  failed_when: kasm_package is not defined

- include_tasks: unarchive-kasm.yml
  when: kasm_exist.stdout == ""

- include_tasks: install-kasm.yml
  when: kasm_exist.stdout == ""

- include_tasks: persistent-storage.yml
  when: persistent_storage

- include_tasks: show-creds.yml
  when: display_creds
